#!/bin/sh

# PROVIDE: commento
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

. /etc/rc.subr

desc="Commento daemon"
name=commento
rcvar=commento_enable

load_rc_config $name

: ${commento_enable:=NO}

commento_env="COMMENTO_ORIGIN=https://commento.example.com \
COMMENTO_PORT=8080 \
DATABASE_URL=commento:123@/commento?charset=utf8&parseTime=True&loc=Local \
COMMENTO_STATIC=/usr/local/share/commento"
commento_user=www

command="/usr/local/bin/commento"
command_args=" >> /var/log/commento/${name}.log 2>&1 &"

run_rc_command "$1"
