[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  # unfortunately, lib/pq doesn't have semver-ed releases yet
  # TODO: don't use revisions, use a proper version once this is solved:
  #   https://github.com/lib/pq/issues/637
  name = "github.com/lib/pq"
  revision = "90697d60dd844d5ef6ff15135d0203f65d2f53b8"

[[constraint]]
  # html2md doesn't have semver-ed releases yet either
  # TODO: use a version once this is solved:
  #   https://github.com/lunny/html2md/issues/8
  name = "github.com/lunny/html2md"
  revision = "13aaeeae9fb293668db3ef1e145064684735f3ce"

[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  version = "1.0.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5.1"

[prune]
  go-tests = true
  unused-packages = true
